apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: allreservationsdeleted
spec:
  broker: default
  filter:
    attributes:
      type: ALL_RESERVATIONS_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reservationadded
spec:
  broker: default
  filter:
    attributes:
      type: RESERVATION_ADDED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reservationdeleted
spec:
  broker: default
  filter:
    attributes:
      type: RESERVATION_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reservationreplaced
spec:
  broker: default
  filter:
    attributes:
      type: RESERVATION_REPLACED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-query-event-processor
