apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: owner-query-event-processor
  namespace: resource-scheduler
spec:
  template:
    metadata:
      name: owner-query-event-processor-v1
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/boosey/owner-query-event-processor