apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: owneradded
spec:
  filter:
    attributes:
      type: RESOURCE_ADDED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor