apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: ownerreplaced
spec:
  filter:
    attributes:
      type: RESOURCE_REPLACED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor