apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: allownersdeleted
spec:
  broker: default
  filter:
    attributes:
      type: ALL_OWNERS_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: owneradded
spec:
  broker: default
  filter:
    attributes:
      type: OWNER_ADDED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ownerdeleted 
spec:
  broker: default
  filter:
    attributes:
      type: OWNER_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ownerreplaced
spec:
  broker: default
  filter:
    attributes:
      type: OWNER_REPLACED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-query-event-processor
