apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: resource-api
  namespace: resource-scheduler
spec:
  selector:
    app: resource-api 
  replicas: 1
  template:
    metadata:
      labels:
        app: resource-api
    spec:
      containers:
        - name: resource-api
          image: docker.io/boosey/resource-api
          ports:
            - containerPort: 8080
