apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: addresource
spec:
  broker: default
  filter:
    attributes:
      type: ADD_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: deleteallresources
spec:
  broker: default
  filter:
    attributes:
      type: DELETE_ALL_RESOURCES
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: deleteresource
spec:
  broker: default
  filter:
    attributes:
      type: DELETE_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: replaceresource
spec:
  broker: default
  filter:
    attributes:
      type: REPLACE_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
      
