apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: addreservation
  annotations:
    knative-eventing-injection: enabled    
spec:
  broker: default  
  filter:
    attributes:
      type: ADD_RESERVATION
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteallreservations
  annotations:
    knative-eventing-injection: enabled    
spec:
  broker: default    
  filter:
    attributes:
      type: DELETE_ALL_RESERVATIONS
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deletereservation
  annotations:
    knative-eventing-injection: enabled    
spec:
  broker: default    
  filter:
    attributes:
      type: DELETE_RESERVATION
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: replacereservation
  annotations:
    knative-eventing-injection: enabled    
spec:
  broker: default    
  filter:
    attributes:
      type: REPLACE_RESERVATION
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reservation-command-event-processor
      
