apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: addowner
spec:
  filter:
    attributes:
      type: ADD_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-command-event-processor