apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: addowner
spec:
  broker: default  
  filter:
    attributes:
      type: ADD_OWNER
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteallowners
spec:
  broker: default  
  filter:
    attributes:
      type: DELETE_ALL_OWNERS
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteowner
spec:
  broker: default  
  filter:
    attributes:
      type: DELETE_OWNER
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: replaceowner
spec:
  broker: default  
  filter:
    attributes:
      type: REPLACE_OWNER
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: owner-command-event-processor
      
