apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: allresourcesdeleted
spec:
  filter:
    attributes:
      type: ALL_RESOURCES_DELETED
  broker: default      
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: resourceadded
spec:
  filter:
    attributes:
      type: RESOURCE_ADDED
  broker: default      
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: resourcedeleted
spec:
  filter:
    attributes:
      type: RESOURCE_DELETED
  broker: default      
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-query-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: resourcereplaced
spec:
  broker: default
  filter:
    attributes:
      type: RESOURCE_REPLACED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-query-event-processor
