apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: availability-command-event-processor
  namespace: resource-scheduler
spec:
  template:
    metadata:
      name: availability-command-event-processor-v5
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/boosey/availability-command-event-processor