kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: owner-api
  namespace: resource-scheduler
  labels:
    app: owner-api
    app.kubernetes.io/component: owner-api
    app.kubernetes.io/instance: owner-api
    app.openshift.io/runtime-namespace: resource-scheduler
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - owner-api
        from:
          kind: ImageStreamTag
          namespace: resource-scheduler
          name: 'owner-api:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 3
  test: false
  selector:
    app: owner-api
    deploymentconfig: owner-api
  template:
    metadata:
      labels:
        app: owner-api
        deploymentconfig: owner-api
    spec:
      containers:
        - name: owner-api
          image: docker.io/boosey/owner-api
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
