apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: availability-query-rest    
  namespace: resource-scheduler
  labels:
    app: availablity-api
    app.kubernetes.io/component: availability-query-rest
    app.kubernetes.io/instance: availability-query-rest
    app.kubernetes.io/part-of: Availability
    app.openshift.io/runtime-namespace: resource-scheduler  
spec:
  triggers:
    - type: ConfigChange
  selector:
    app: availability-query-rest
  replicas: 1
  revisionHistoryLimit: 0  
  template:
    metadata:
      labels:
        app: availability-query-rest
    spec:
      containers:
        - name: availability-query-rest
          image: docker.io/boosey/availability-query-rest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: availability-query-rest
  namespace: resource-scheduler
  labels:
    app: availability-query-rest
    app.kubernetes.io/component: availability-query-rest
    app.kubernetes.io/instance: availability-query-rest
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: Availability
    app.openshift.io/runtime: ''
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: availability-query-rest
    deploymentconfig: availability-query-rest

