apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: allavailabilitysdeleted
spec:
  filter:
    attributes:
      type: ALL_AVAILABILITYS_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-query-event-processor
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: availabilityadded
spec:
  filter:
    attributes:
      type: AVAILABILITY_ADDED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-query-event-processor
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: availabilitydeleted
spec:
  filter:
    attributes:
      type: AVAILABILITY_DELETED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-query-event-processor
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: availabilityreplaced
spec:
  filter:
    attributes:
      type: AVAILABILITY_REPLACED
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-query-event-processor
