apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: addresource
spec:
  filter:
    attributes:
      type: addResource
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-commands-server