apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: availability-api    
  namespace: resource-scheduler
  labels:
    app: owner-api
    app.kubernetes.io/component: availability-api
    app.kubernetes.io/instance: availability-api
    app.kubernetes.io/part-of: Availability
    app.openshift.io/runtime-namespace: resource-scheduler  
spec:
  triggers:
    - type: ConfigChange
  selector:
    app: availability-api
  replicas: 1
  template:
    metadata:
      labels:
        app: availability-api
    spec:
      containers:
        - name: availability-api
          image: docker.io/boosey/availability-api
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      restartPolicy: Always
