apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: deleteallresources
spec:
  filter:
    attributes:
      type: DELETE_ALL_RESOURCES
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor