apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: addresource
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default  
  filter:
    attributes:
      type: ADD_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteallresources
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default  
  filter:
    attributes:
      type: DELETE_ALL_RESOURCES
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteresource
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default  
  filter:
    attributes:
      type: DELETE_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: replaceresource
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default  
  filter:
    attributes:
      type: REPLACE_RESOURCE
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: resource-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: addavailability
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default 
  filter:
    attributes:
      type: ADD_AVAILABILITY
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteallavailabilities
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default 
  filter:
    attributes:
      type: DELETE_ALL_AVAILABILITIES
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: deleteavailability
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default 
  filter:
    attributes:
      type: DELETE_AVAILABILITY
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-command-event-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: replaceavailability
  annotations:
    knative-eventing-injection: enabled  
spec:
  broker: default 
  filter:
    attributes:
      type: REPLACE_AVAILABILITY
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: availability-command-event-processor
           
