kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  name: resource-api
  namespace: resource-scheduler
  labels:
    app: resource-api
    app.kubernetes.io/component: resource-api
    app.kubernetes.io/instance: resource-api
    app.openshift.io/runtime-namespace: resource-scheduler
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - resource-api
        from:
          kind: ImageStreamTag
          namespace: resource-scheduler
          name: 'resource-api:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: resource-api
    deploymentconfig: resource-api
  template:
    metadata:
      labels:
        app: resource-api
        deploymentconfig: resource-api
    spec:
      containers:
        - name: resource-api
          image: docker.io/boosey/resource-api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
