apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: eventsservicegrpc    
  namespace: resource-scheduler
  labels:
    app: eventsservicegrpc
    app.kubernetes.io/component: eventsservicegrpc
    app.kubernetes.io/instance: eventsservicegrpc
    app.kubernetes.io/part-of: Events
    app.openshift.io/runtime-namespace: resource-scheduler  
spec:
  triggers:
    - type: ConfigChange
  selector:
    app: eventsservicegrpc
  replicas: 1
  revisionHistoryLimit: 0  
  template:
    metadata:
      labels:
        app: eventsservicegrpc
    spec:
      containers:
        - name: eventsservicegrpc
          image: docker.io/boosey/eventsservicegrpc
          env:
            - name: mongopwdadmin
              valueFrom:
                secretKeyRef:
                  name: mongo-event-store
                  key: database-admin-password
            - name: mongopwd
              valueFrom:
                secretKeyRef:
                  name: mongo-event-store
                  key: database-password
            - name: mongouser
              valueFrom:
                secretKeyRef:
                  name: mongo-event-store
                  key: database-user
          ports:
            - name: grpc-server
              containerPort: 9000
              protocol: TCP          
          imagePullPolicy: Always
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: eventsservicegrpc
  namespace: resource-scheduler
  labels:
    app: eventsservicegrpc
    app.kubernetes.io/component: eventsservicegrpc
    app.kubernetes.io/instance: eventsservicegrpc
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: Events
    app.openshift.io/runtime: ''
    app.openshift.io/runtime-version: latest
spec:
  ports:
    - name: 9000-tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: eventsservicegrpc
    deploymentconfig: eventsservicegrpc

